name: JPF Runner

on:
  push:

jobs:
  run-jpf:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 53c8c8d6d0b957e9d4ae02f99d5993d5e699d522
    
    - name: Set up JDK 17 for project 
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven
            
    - name: Build project with JDK 17
      run: | 
        for dir in */ ; do
          if [ -f "$dir/pom.xml" ]; then
            mvn -f "$dir/pom.xml" clean install \
                        -Dmaven.compiler.source=11 \
                        -Dmaven.compiler.target=11 \
                        -Djakarta.mail.version=2.0.1 \
                        -Dspring-boot.version=2.6.6 \
                        -DadditionalDependencies="com.sun.mail:jakarta.mail:2.0.1" \
                        -DskipTests
          fi
        done

    - name: Set up JDK 11 for JPF and project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Clone and build jpf-core
      run: |
        git clone https://github.com/javapathfinder/jpf-core.git /tmp/jpf-core
        cd /tmp/jpf-core
        ./gradlew buildJars

    - name: Run JPF on JAR files
      run: |
        #!/bin/bash

        directory=$(pwd)
        runjpf_jar="/tmp/jpf-core/build/RunJPF.jar"
        jar_files=$(find "$directory" -type f -name "*.jar")

        for jar_file in $jar_files; 
        do
            jar_dir=$(dirname "$jar_file")
            main_class=$(unzip -p "$jar_file" META-INF/MANIFEST.MF | grep -i 'Main-Class' | awk -F': ' '{print $2}' | tr -d '\r')

            if [ -z "$main_class" ]; then
                echo "Main class not found in $jar_file, skipping..."
                continue
            fi

            command="java -jar $runjpf_jar +classpath=$jar_file $main_class"
            $command
        done
